language: java

jdk:
  - oraclejdk11

sudo: false
env:
    global:
        #key for github
        #GITHUB_OAUTH_TOKEN
        - secure: "TV0evIpZSjayhe5iglkXOgib2+EtwbFf/IyR8J3+DW+sjoEhCjKYQeUhMYqmbOeJ0g6Q+ecW1l1UsQuMUeCetN2Ge8QbBcjvcJE/cS+e94zOOrNFjNVuhOH8Fi6VXY0eqp6H9zCH6kRdPkElpFd2nddEPZml1gmbZG5plOgmN/u764J11YLOBFjw2eMIzcDtyya6W3xnAw3JhzV9FpuZ+ogzV63SZVcPB5vEPMJLmwyJXZjsis1nAjSr0OSAq8qQPvsRAg1UCHQWAA/1d03/ifZhROMgTMmSrIBPiTj7Tldb5txTXy2cvlaXEYvt3A9UUZDbmobP8Qx0eiO3gIXQC8rR4eSEHTHUx7VxaqsFMyNIJk+M32ripVe4hOM2RpRqoKsKPms1Af1LXXZA08zP45LlYWi76vvkjdaXhozGIcI7ElZ0oFviJa9T4WUko4jedB83A5luCL7IzdwLPPHBkGDjjwfhx8BpekKVnZIe48Zah2/mbFEhWGQ92gEvZasdIGCEhxEgSjLUCySMKuVmSKZW+wGnO68cAZvd0RU7kvxmJlCS3quZYRK9IJAiEDxfqWLgqcdnhVJtwaQNXu4pwEjMziPiKGrUMQSZgnsEmg0wElpgTfP1tSZT014r7+Ww4uLsdj+M7SQvwq2EC4DhJNedJkvKck7ABlQvNPT5zII="
        - environment=test
        #sonatype credentials
        #OSSRH_JIRA_USERNAME
        - secure: "2UMT0mpcnPTfFJi9vdxsK7xScxvZEjTPmTuG/2Cmdwx0Y35w3Fh5m3+2XqKyVEBqHRKRCHmRYQ7p1Gj1kCoNRb2nL7X4wExA0f86fF4uEzCsBiV6UsXP/7CJfThPPHzjXqL4lWIkDVXA6GSe6Cez33INhOLbmYQwbA8TrmKJmCq11/iEZygQflhXwvCfS+sdmhiknwyHsOztqTOrBW+kI+6ME+IEBQLatIS+tGjvt7RfOKBFYN0uYxVVQpW0wPiw5/L+3YSFW22jgIUzTJcenjheiCCjIaBVSDjNKX5gU8QchzeJpHiqKCFNY+nChje1bW3CArT/w+QeD0IjtxSndh8UA6PkjyoX9ZiTP7I3V0KPPTh4C4JkhvNa1Z091D1e28SRb77tdBe7063V/ZLEutgToICqSTL3Qbr1NeEMKX+DBMSKd7CBM8G/Dm3avzqKPsuQsl8b84gBpH4DiNZ+osMIp5Ijt+q+aOPMRvndO2aK4rcFN9yjxQZ8ucohebSvvL6d/W+vRag/lRTFSMT6MhPkrmbkcv58jefUKtAA5p9s2BPfPQOIWxRbyoEF/tTdSzDSOotrCD1Q4oQFRgQAv55/bC7J/5/VDElRRxqARFqEbxhCzKl6PzfpQeiWgozhbnzbzvrZA0sbTcVrIgwtQuRAFY15JcaYvuQeZvETxRU="
        #OSSRH_JIRA_PASSWORD
        - secure: "gpitDfvtK1EWBFbATAcC0Zh4O5CcACnlAxiSXruau1AiLmy8KlDv40hQwIqhyWTYhQEaMIblcL0SZXU3b4U6EH8epjYqXKOjmZcuMgErXEh5My9wC8wS4txPvQi1BDaN8aMrxmvCNFmHCUdPXRgc8uXx4ndxjC+ncrVmQZs+fldts2l1aaNbVcszQKRu2uY24xe5xN/TLEFhAXI5OYWh5vlBdb0CPosOA0RPlfv/r7/G2IXXrOXimM4cttB4Qw+IIrosnZmhfOsJkOdbxPIM4ykcia0zgLkxy3sPojzVDuD0jAxtFPVwFuKmnP34bixs2GqkWUxBXCPLp36aKpVUM9zAtUmlDcq5mg5GObMPmZr0HanL17f7UVWj2qaaNk2XJb048ygrEB9KVLgwGEoaO0sdIFNAYe+I/t66nKvVqHKY6ZJnGRk4qmrdgFouf6l+I675brgz0m8+OCEqk7ucouQ17dIjbZFLwSCLb8dmbjxxAs1aUu3EoiGowQD7Ui5WQzuqLgEPQH38MvgEV1yR5z0/1cyMLlnHKkrJXJM1k3b4qppEzCEz8u1OtxewL5zdJCGHVReAC2r1kmJBxTB2XWmAiaJsR8egyBBtj2DhOnexnUgr7GUdZjQlKiBNHjYymWV7xKimNMLX8mqfLXluWl9sE+RS1PMmnSZP+S45Nqs="
        #signing key
        #GPG_KEY_NAME
        - secure: "PRWoCc1v65KACD//NPpHP+t8U3kYVaQG3UP4FqTiEhEI+qLPtO94DiQQ8AZz42zT5d2L3MPJyN6UrywTuUXT2B/vEcK4aYQHPezqC02IYIFCDo+MCta2PGN2fQav/SYIH2ME3x4dyAzmhazHRVeH39ALqaM0e6RrmusiirlRDWs3thhJxzL+BZv6r1c3JMcHyo2zOiODHSy28+jGjK9syC6o7aMoBzzXArWWkN1umRgewAbSM2R13K+TCG3K3CFJXNaD9PYxdnMvg6btAzxZ6vh65C9QRHNFYyKgqUwCprxN3baq/9/2GRdxkCLwLS9cvMVfjLcLtvbEc+vNsx5puD3qFiaMIog3wb4cF/qbnt+aqlWzrKxMPVhvPw6quILKJ3cNgEqHu1V0DVSFXsDK1rumGI7T81j/EUpYdXXpKrZ30idVQ7u59SX11CSBsFSj2Oxu3ktlsIoN76U3x+u1pZ3xniABGm5phHUoEtn7GIui/v0RsVyjwGoXEUkndSHQAvs8NoxGm3WfJKsPiU5iYoUrfMLLW1JIuA6GMrNp6J+Z27JOcd9OeD5TBAvKA+RIwHJRA2fNGfuMFaQfJTqftcIaOGLS8fwEsueGAhyNKreEupdXCYTQYfRY0d5k3Ww/ZO1YJfUoFWcVcrToD/9hzxGBXpyCYL8i3yHGYx2ARBE="
        #GPG_PASSPHRASE
        - secure: "hUTCDQb8RGRC/QlLp0g8Z5d13RdfV/eByKJyi2WX932nLaQtrfyO3KDLl9Mu757gpP/kLA/cBT4VzwguLcUIXm/tQMi39hVN+go9qiY8Znsu0ot3x27gKAzLS5U8qW1u7pDkiF+zcMJcf4MRa0roY0dnEaTaSe8iivykShDlpK2wRz3OBPfWyYuWK+YTuT507dxrTIw6uzUUYHnV2Ul8aj63qdnWQtqHjiPM/1kq2zopSLFo8YjRGJyt9BJ+bUyCNh6MuoSpEekyPQJwIJpKs//W0EV4Bz2C10TCVyJgv4u2sxwajGEa9eYTFaLTVwTJPY+DtoOBLd6doTaFbIFhcQ1cVsqXFrgrpfUnUwcCBaf1RSuAHHAqH8Cs4cQwEBwfi9QPb/PTxKOgkX5zksWiYnxq9rxNq0d6vexwdfGt30GTBpFyociTDCHJazF8RA6KFPv6PbkPTNnMs44CMqiQqGjC3bvnj9sjsF7delaOqo1BBQ+0u1u2jfAkpaAdKv1BCD30s85s2IaPhWVNCB6/Zlh1pDhHMFbcFL2mEuJ85NwSZtSIHKlzw63qoQo+SxL5L1ezii48EfpsKbOKW1j096OGXjwGvs5g9jr20+uNnEzYYLbArk4nTXi/F/sz7vMkV5Ntd6Eujgt4xp1U3S68Eaexg4R9tgv8A4ek3z1iMYM="

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "UP408LZjGGQcG04AJs/lxgPPnggejkYk2S85eE+OhjO541vt0ANZrCeSzr3+CVWbjhJmqFeJCJsQ/ekdJCI09zgWzyvCJ2EeXN2IevK6sIl7C/0Gl5CZeHJAKBWlJcUXIs8WSURHOAreYDZpa/l4EsTVZFGzd7dBhwIc36YmZdhOBXmF2oSiLZFUckoj8RxDnm7osDSoMkPgaT1eFJMcXIwAGSP9Az5lD/yvkkXAb281pou6qoUy/l2SIiUy7MoWXT6Fnmdo4zlWkfCncSDCI62VaMJoDFj5sl/rajdedmLdrefw1raecOefkB7wiqCtTRK60vEAbo/WbXk8mcheoxdL3ED4vIKFJQiZagD+H5P0sLMbqamVB9XsssjXk0dcBKaLf2Ozj3db3OoOQx3yYYXapAPZvmLqFxZOSz1Lb0iOgyxAuVNHUguBKB10jKo1Iu/xDf0S8Luj8roN6294av4bpJR7T3WghhHwam8Y6VvrO9AnWmUJFOg/rpZeRlOOIVBcOdOcdTS8jVvmzkU5qQqdCmbZ+EEZRO6Wvy6jN+8DHDoY0URtxd8LCFWV2plxp4lFWMHhN3nWZQb97wGKw2q8QYvS0rSGAEujkmM91Gwcnw6JzC96mZHe/Y+xEdD/e3qDtyUTP7qBeskbulJq4vYAsuqbZaZHodg1Ecc90WU="

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script:
  - travis_wait 50 mvn clean jacoco:prepare-agent install jacoco:report --quiet -P !build-extras
  - mvn site -Djacoco.skip -DskipTests --quiet -P !build-extras
  - sonar-scanner

cache:
  directories:
    - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: master

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh
